doctrine:
    orm:
        mappings:
            DoopSyliusProductVariantAttributePlugin:
                is_bundle: true
                type: xml
                dir: Resources/config/mapping/orm
                prefix: Doop\SyliusProductVariantAttributePlugin\Entity
                alias: DoopSyliusProductVariantAttributePlugin
