doop_sylius_product_variant_attribute_plugin_admin_product_variant_attribute:
    resource: |
        alias: sylius.product_variant_attribute
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show', 'create']
        redirect: update
        grid: doop_sylius_product_variant_attribute_plugin_admin_product_variant_attribute
        permission: true
        vars:
            all:
                subheader: doop_sylius_product_variant_attribute_plugin.ui.manage_attributes_of_your_products
                templates:
                    form: "@DoopSyliusProductVariantAttributePlugin/Admin/ProductVariantAttribute/_form.html.twig"
            index:
                icon: cubes
    type: sylius.resource

doop_sylius_product_variant_attribute_plugin_admin_product_variant_attribute_create:
    path: /product-variant-attributes/{type}/new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product_variant_attribute:createAction
        _sylius:
            section: admin
            factory:
                method: createTyped
                arguments:
                    type: $type
            template: "@SyliusAdmin/Crud/create.html.twig"
            redirect: sylius_admin_product_variant_attribute_update
            permission: true
            vars:
                subheader: doop_sylius_product_variant_attribute_plugin.ui.manage_attributes_of_your_products
                templates:
                    form: "@DoopSyliusProductVariantAttributePlugin/Admin/ProductVariantAttribute/_form.html.twig"
                route:
                    name: doop_sylius_product_variant_attribute_plugin_admin_product_variant_attribute_create
                    parameters:
                        type: $type

doop_sylius_product_variant_attribute_plugin_admin_get_attribute_types:
    path: /variant-attribute-types
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_variant_attribute:getAttributeTypesAction
        template: "@DoopSyliusProductVariantAttributePlugin/Admin/ProductVariantAttribute/Types/attributeTypes.html.twig"

doop_sylius_product_variant_attribute_plugin_admin_get_product_variant_attributes:
    path: /variant-attributes
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_variant_attribute:renderAttributesAction
        template: "@DoopSyliusProductVariantAttributePlugin/Admin/ProductVariant/Attribute/attributeChoice.html.twig"

doop_sylius_product_variant_attribute_plugin_admin_render_variant_attribute_forms:
    path: /variant-attribute-forms
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_variant_attribute:renderAttributeValueFormsAction
        template: "@DoopSyliusProductVariantAttributePlugin/Admin/ProductVariant/Attribute/attributeValues.html.twig"
